[pytest]
# Directorio donde están los tests
testpaths = tests

# Mostrar prints y logs durante los tests (útil para depurar)
log_cli = true
log_cli_level = WARNING

# Mostrar tests lentos
addopts =
    -v
    --tb=short
    --cov=app
    --cov-report=term-missing
    --cov-fail-under=70
